import Link from 'next/link';
import { notFound } from 'next/navigation';
import { RouteMap } from '../../../components/RouteMap';
import { RouteCard } from '../../../components/RouteCard';
import { RouteFacts } from '../../../components/RouteSections';
import { getRegion, getRouteBySlug, nearbyRoutes, routes } from '../../../lib/routes';
export async function generateStaticParams(){return routes.map(r=>({slug:r.slug}))}
export async function generateMetadata({params}){const {slug}=await params; const r=getRouteBySlug(slug); return {title:r?`${r.title} | Trek Desert Maroc`:'Trekking Route | Trek Desert Maroc',description:r?.summary||'Detailed Morocco trekking route file.'}}
export default async function TrekDetailPage({params}){const {slug}=await params; const route=getRouteBySlug(slug); if(!route) notFound(); const region=getRegion(route.region); const nearby=nearbyRoutes(route.slug,3); return <><section className={`route-detail-hero landscape-${route.type}`}><div className="container route-hero-grid"><div><span className="eyebrow">{route.area}</span><h1>{route.title}</h1><p>{route.summary}</p><div className="route-crumbs"><span>{route.start}</span>{route.via.slice(0,3).map(p=><span key={p}>{p}</span>)}<span>{route.end}</span></div><div className="hero-actions"><Link className="btn btn-primary" href="/contact">Request this route</Link><Link className="btn btn-secondary" href="/routes">Back to routes</Link></div></div><div className="route-photo-large"><span>{route.style}</span><strong>{route.start} → {route.end}</strong></div></div></section><section className="section atlas-section"><div className="container"><RouteFacts route={route}/></div></section><section className="section map-showcase"><div className="container"><div className="section-head"><div><span className="eyebrow">Route map</span><h2>{region?.title || route.area}</h2></div><p>{region?.summary}</p></div><RouteMap type={route.type}/></div></section><section className="section"><div className="container route-content-grid"><div><div className="section-head compact"><div><span className="eyebrow">Day-by-day route logic</span><h2>Stages and itinerary</h2></div></div><div className="stages-list">{route.stages.map((s,i)=><div className="stage-card" key={s[0]}><span className="stage-number">{s[0]}</span><div><h3>{s[1]}</h3><p>{s[2]}</p></div></div>)}</div></div><aside className="route-sidebar"><div className="sidebar-card"><h3>Route highlights</h3><ul>{route.highlights.map(x=><li key={x}>{x}</li>)}</ul></div><div className="sidebar-card"><h3>Logistics</h3><p>{route.logistics}</p></div><div className="sidebar-card"><h3>Best for</h3><p>{route.forWhom}</p></div></aside></div></section><section className="section atlas-section"><div className="container"><div className="section-head"><div><span className="eyebrow">Nearby route files</span><h2>Build the bigger route network.</h2></div><p>Each route page connects to nearby routes so the website becomes a real trekking atlas over time.</p></div><div className="routes-grid">{nearby.map(item=><RouteCard key={item.slug} route={item}/>)}</div></div></section><section className="section"><div className="container cta-panel"><div><span className="eyebrow">Custom planning</span><h2>Turn this route into a private trek.</h2><p>Send your dates, group size, walking level and comfort preference. The route can be shortened, extended or connected to another area.</p></div><Link className="btn btn-primary" href="/contact">Plan this route</Link></div></section></>}
