import Link from "next/link";
import { BlogCard } from "../components/BlogCard";
import { SymbolIcon } from "../components/SymbolIcon";
import { TourCard } from "../components/TourCard";
import { TrekMap } from "../components/TrekMap";
import { departureOf, fallbackPosts, fallbackTours, getBlogPosts, getServices, matches, mergeWithFallback } from "../lib/api";
export const revalidate = 120;
export default async function HomePage() {
  const services = await getServices({ per_page: 60 });
  const posts = await getBlogPosts({ per_page: 9 });
  const trekking = services.filter((item) => matches(item, ["trek", "hiking", "walk", "desert", "sahara", "atlas", "toubkal"]));
  const scheduled = services.filter((item) => matches(item, ["scheduled", "departure", "group"]) || departureOf(item) !== "Private dates available");
  const finalTours = mergeWithFallback(trekking.length ? trekking : services, fallbackTours, 6).slice(0, 6);
  const finalPosts = mergeWithFallback(posts, fallbackPosts, 3).slice(0, 3);
  return <>
    <section className="hero"><TrekMap/><div className="container hero-content"><span className="eyebrow">Trekking in Morocco • Sahara • Atlas • Retreats</span><h1 className="display">A website built for walking Morocco.</h1><p>Trek Desert Maroc is not a generic tour catalog. It is a trekking-first website for Sahara desert treks, Atlas mountain walking journeys, scheduled departures, private trails and yoga trekking retreats.</p><div className="hero-actions"><Link className="btn btn-primary" href="/tours">Explore Trekking Routes →</Link><Link className="btn btn-light" href="/yoga-trek-retreat">Yoga Trek Retreats ↗</Link></div><div className="symbol-grid">{[["boot","Walking"],["compass","Route"],["mountain","Atlas"],["camel","Camel Support"],["tent","Camp"],["sun","Desert"]].map(([icon,label])=><div className="symbol-card" key={label}><SymbolIcon name={icon}/><span>{label}</span></div>)}</div></div><div className="hero-badges"><div className="hero-badge"><strong>Sahara Treks</strong><span>M’Hamid, Erg Chigaga, dunes and wild desert routes.</span></div><div className="hero-badge"><strong>Atlas Walks</strong><span>Mountain valleys, village trails and Toubkal routes.</span></div><div className="hero-badge"><strong>Scheduled Tours</strong><span>Future fixed-date departures for small trekking groups.</span></div><div className="hero-badge"><strong>Yoga Retreats</strong><span>Walking, breath, silence and Moroccan landscapes.</span></div></div></section>
    <section className="section"><div className="container"><div className="section-head"><div><span className="eyebrow">Trekking identity</span><h2 className="display">Every section should say: this is a trekking company.</h2></div><p>The design now uses trail symbols, walking route cards, desert and mountain visuals, difficulty information, route rhythm, and scheduled departure blocks.</p></div><div className="grid-4">{[["boot","Walking Days","Clear walking rhythm, terrain, pace and daily experience."],["map","Route Logic","Sahara, Atlas, nomadic trails and private route planning."],["tent","Camp & Lodges","Desert camps, village stays and mountain accommodation."],["compass","Guided Journey","Local guides, route knowledge and safety-focused planning."]].map(([icon,title,text])=><div className="focus-card" key={title}><span className="icon-circle"><SymbolIcon name={icon}/></span><h3>{title}</h3><p>{text}</p></div>)}</div></div></section>
    <section className="section section-alt"><div className="container"><div className="section-head"><div><span className="eyebrow">Featured trekking programs</span><h2 className="display">Morocco journeys built around walking.</h2></div><p>If the admin has only a few tours now, the website still feels complete because planned route cards fill the trekking structure until more tours are added.</p></div><div className="grid-3">{finalTours.map((tour,index)=><TourCard key={tour.id || tour.slug || index} tour={tour}/>)}</div></div></section>
    <section className="section"><div className="container grid-wide"><div><span className="eyebrow">How trekking is explained</span><h2 className="display" style={{fontSize:72,margin:"16px 0"}}>More information before travelers ask.</h2><p style={{color:"var(--muted)",lineHeight:1.8}}>The site should educate visitors before they contact you: walking hours, terrain, comfort level, camel support, guides, camp style, difficulty and best season.</p></div><div className="route-steps">{[["01","Choose the landscape","Sahara dunes, wild desert plateaus, Atlas valleys or retreat-style routes."],["02","Understand the walking level","Daily walking rhythm, terrain, pace and fitness expectations are explained clearly."],["03","See the support style","Guides, camel/mule support, camps, lodges, meals and transfers are shown before booking."],["04","Pick private or scheduled","Travelers can request a private trek or join a planned future departure."]].map(([number,title,text])=><div className="route-step" key={number}><span className="step-number">{number}</span><div><h3>{title}</h3><p>{text}</p></div></div>)}</div></div></section>
    <section className="section section-dark"><div className="container"><div className="section-head"><div><span className="eyebrow">Trek essentials</span><h2 className="display">The details that make a trekking site trustworthy.</h2></div><p>These content blocks should appear across tour pages and future itinerary pages.</p></div><div className="trek-info">{[["mountain","Terrain","Dunes, rocky plateaus, valleys, passes and village paths."],["boot","Walking Hours","Clear daily walking rhythm and realistic pace information."],["camel","Support","Camel or mule support depending on the region and route."],["tent","Nights","Desert camps, bivouacs, guesthouses or mountain lodges."]].map(([icon,title,text])=><div className="info-strip" key={title}><SymbolIcon name={icon}/><h3>{title}</h3><p>{text}</p></div>)}</div></div></section>
    <section className="section"><div className="container grid-2"><div><span className="eyebrow">Scheduled departures</span><h2 className="display" style={{fontSize:64,margin:"15px 0"}}>Future group dates, shown clearly.</h2><p style={{color:"var(--muted)",lineHeight:1.8}}>Use admin fields for departure dates later. If no date exists yet, the site displays private dates available.</p></div><div className="schedule-list">{(scheduled.length ? scheduled : finalTours).slice(0,4).map((item,index)=><Link key={item.id || item.slug || index} href={item.slug ? `/tour/${item.slug}` : "/contact"} className="schedule-item"><div><span className="eyebrow">Departure</span><h3>{item.title || item.name}</h3><p>{item.excerpt || "Morocco trekking departure."}</p></div><span className="date-pill">{departureOf(item)}</span></Link>)}</div></div></section>
    <section className="section section-alt"><div className="container"><div className="section-head"><div><span className="eyebrow">Trekking blog</span><h2 className="display">Guides that support trekking sales.</h2></div><p>The blog should not be generic. It should answer real trekking questions: when to go, what to pack, walking difficulty, Sahara vs Atlas, and yoga trekking retreats.</p></div><div className="grid-3">{finalPosts.map((post,index)=><BlogCard key={post.id || post.slug || index} post={post}/>)}</div></div></section>
  </>;
}
